
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXM = 9;
  public static final int OP = 5;
  public static final int CP = 6;
  public static final int CO = 8;
  public static final int QDASH = 4;
  public static final int CM = 7;
  public static final int DASH = 3;
  public static final int ATOM = 10;
  public static final int EOF = 0;
  public static final int VAR = 11;
  public static final int DOT = 2;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "DASH",
  "QDASH",
  "OP",
  "CP",
  "CM",
  "CO",
  "EXM",
  "ATOM",
  "VAR"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[9]=new String("EXM");
		TT[5]=new String("OP");
		TT[6]=new String("CP");
		TT[8]=new String("CO");
		TT[4]=new String("QDASH");
		TT[7]=new String("CM");
		TT[3]=new String("DASH");
		TT[10]=new String("ATOM");
		TT[0]=new String("EOF");
		TT[11]=new String("VAR");
		TT[2]=new String("DOT");
		TT[1]=new String("error");
	}
public String getTT(int i){return TT[i];}
}

