
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP = 6;
  public static final int SC = 12;
  public static final int CP = 7;
  public static final int CO = 10;
  public static final int CM = 11;
  public static final int DASH = 3;
  public static final int STAR = 2;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int EQ = 4;
  public static final int VAR = 13;
  public static final int SEP = 15;
  public static final int GT = 8;
  public static final int error = 1;
  public static final int SL = 9;
  public static final int INUM = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STAR",
  "DASH",
  "EQ",
  "PLUS",
  "OP",
  "CP",
  "GT",
  "SL",
  "CO",
  "CM",
  "SC",
  "VAR",
  "INUM",
  "SEP"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[6]=new String("OP");
		TT[12]=new String("SC");
		TT[7]=new String("CP");
		TT[10]=new String("CO");
		TT[11]=new String("CM");
		TT[3]=new String("DASH");
		TT[2]=new String("STAR");
		TT[0]=new String("EOF");
		TT[5]=new String("PLUS");
		TT[4]=new String("EQ");
		TT[13]=new String("VAR");
		TT[15]=new String("SEP");
		TT[8]=new String("GT");
		TT[1]=new String("error");
		TT[9]=new String("SL");
		TT[14]=new String("INUM");
	}
public String getTT(int i){return TT[i];}
}

